[package]
name = "lfbs"
version = "0.1.0"
edition = "2021"
description = "Lock-free stack with batched pop"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
num_cpus = "1"
